---
# In Kubernetes a deployment is used to manange pods.
# For this task, you should have one deployment for the backend code execution
# API so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: task3-ui
  labels:
    app: task3-ui
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3-ui
  template:
    metadata:
      labels:
        app: task3-ui
      namespace: task3
    spec:
      containers:
        - name: task3-ui
          image: us.gcr.io/tzhong1-project1/task3-ui:v6
          ports:
          - containerPort: 5000
---
# For this task, you should have one deployment for the frontend code execution UI
# so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: task3-service
  labels:
    app: task3-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3-service
  template:
    metadata:
      labels:
        app: task3-service
    spec:
      containers:
        - name: task
          image: us.gcr.io/tzhong1-project1/task3-back:v4
          ports:
          - containerPort: 6000
---
# A service is an abstraction that enables traffic to be routed from the network to a
# specific pod. This service should double as a Load Balancer.
# https://kubernetes.io/docs/concepts/services-networking/service/
#
#
# You should create a service for each deployment you have created above.
# https://v1-8.docs.kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: task3-ui
  labels:
    app: task3-ui
# Complete the service spec based on the documentation provided in:
# https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#service-v1-core
spec:
  selector: 
    app: task3-ui
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: task3-service
  labels:
    app: task3-service
spec:
  selector: 
    app: task3-service
  ports:
  - port: 80
    targetPort: 6000
  type: LoadBalancer
